name: Build ToIcey OS ISO
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ISO
        uses: archlinux/archiso-action@v2
        id: build
        with:
          profile_path: profile
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToIceyOS-ISO
          path: /tmp/archiso/out/*.iso
          if-no-files-found: warn
